#!/bin/bash


function kl_main () {

        declare -g    KL_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P);
        declare -g -i KL_INTEGER=123;
        declare -g -a KL_INDEXED_ARRAY=();
        declare -g    ONE_ASCII_HEX='^[0-7][0-9a-fA-F]+$';
        declare -g    ONE_ASCII_DEC='^([0-9]|[1-9][0-9]|1[01][0-9]|12[0-7])$';

        function kl_dec2hex () {
                if [[ $* =~ $ONE_ASCII_DEC ]]; then
                        printf %02x "$*";
                else
                        return 1;
                fi;
        };

        function kl_hex2dec () {
                if [[ $* =~ $ONE_ASCII_HEX ]]; then
                        printf %d 0x"$*";
                else
                        return 1;
                fi;
        };

        function kl_hex2raw () {
                if [[ $* =~ $ONE_ASCII_HEX ]]; then
                        printf "\x$*";
                else
                        return 1;
                fi;
        };

        : 'TODO';
        : 'ASCII characters translate (two letter ctrl char and # of columns)';
        : 'The log database (IO interface for a server or a regular file)';
        : 'The tmux interface to deal with status message';
        : 'Setting up the tmux keybindings';
        : 'Setting up the tmux keylogging callback entry point';
        : 'Some list operation';
};


IFS= read -r -d END_BASH_READ tmux_ascii_table <<'END_STD_INPUT'
|	00	^@	C-Space	|
|	01	^A	C-a	|
|	02	^B	C-b	|
|	03	^C	C-c	|
|	04	^D	C-d	|
|	05	^E	C-e	|
|	06	^F	C-f	|
|	07	^G	C-g	|
|	08	^H	C-h	|
|	09	^I	C-i	|
|	0a	^J	C-j	|
|	0b	^K	C-k	|
|	0c	^L	C-l	|
|	0d	^M	C-m	|
|	0e	^N	C-n	|
|	0f	^O	C-o	|
|	10	^P	C-p	|
|	11	^Q	C-q	|
|	12	^R	C-r	|
|	13	^S	C-s	|
|	14	^T	C-t	|
|	15	^U	C-u	|
|	16	^V	C-v	|
|	17	^W	C-w	|
|	18	^X	C-x	|
|	19	^Y	C-y	|
|	1a	^Z	C-z	|
|	1b	^[	C-[	|
|	1c	^\	C-\	|
|	1d	^]	C-]	|
|	1e	^^	C-^	|
|	1f	^_	C-_	|
|	20	 	 	|
|	21	!	!	|
|	22	"	"	|
|	23	#	#	|
|	24	$	$	|
|	25	%	%	|
|	26	&	&	|
|	27	'	'	|
|	28	(	(	|
|	29	)	)	|
|	2a	*	*	|
|	2b	+	+	|
|	2c	,	,	|
|	2d	-	-	|
|	2e	.	.	|
|	2f	/	/	|
|	30	0	0	|
|	31	1	1	|
|	32	2	2	|
|	33	3	3	|
|	34	4	4	|
|	35	5	5	|
|	36	6	6	|
|	37	7	7	|
|	38	8	8	|
|	39	9	9	|
|	3a	:	:	|
|	3b	\\;	\;	|
|	3c	<	<	|
|	3d	=	=	|
|	3e	>	>	|
|	3f	?	?	|
|	40	@	@	|
|	41	A	A	|
|	42	B	B	|
|	43	C	C	|
|	44	D	D	|
|	45	E	E	|
|	46	F	F	|
|	47	G	G	|
|	48	H	H	|
|	49	I	I	|
|	4a	J	J	|
|	4b	K	K	|
|	4c	L	L	|
|	4d	M	M	|
|	4e	N	N	|
|	4f	O	O	|
|	50	P	P	|
|	51	Q	Q	|
|	52	R	R	|
|	53	S	S	|
|	54	T	T	|
|	55	U	U	|
|	56	V	V	|
|	57	W	W	|
|	58	X	X	|
|	59	Y	Y	|
|	5a	Z	Z	|
|	5b	[	[	|
|	5c	\	\	|
|	5d	]	]	|
|	5e	^	^	|
|	5f	_	_	|
|	60	`	`	|
|	61	a	a	|
|	62	b	b	|
|	63	c	c	|
|	64	d	d	|
|	65	e	e	|
|	66	f	f	|
|	67	g	g	|
|	68	h	h	|
|	69	i	i	|
|	6a	j	j	|
|	6b	k	k	|
|	6c	l	l	|
|	6d	m	m	|
|	6e	n	n	|
|	6f	o	o	|
|	70	p	p	|
|	71	q	q	|
|	72	r	r	|
|	73	s	s	|
|	74	t	t	|
|	75	u	u	|
|	76	v	v	|
|	77	w	w	|
|	78	x	x	|
|	79	y	y	|
|	7a	z	z	|
|	7b	{	{	|
|	7c	|	|	|
|	7d	}	}	|
|	7e	~	~	|
|	7f	Bspace	BSpace	|
END_BASH_READ
END_STD_INPUT


if [[ ${BASH_SOURCE[0]} != $0 ]]; then
        : 'The script is sourced';
        : 'Do not do anything here';
else
        : 'The script is executed';
        : 'Invoke the main procedure now';
        kl_main "$@";
fi;


# vi: se et sta ts=8 sw=8 sts=2 :
